"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup
import os

# Config section, change this for each release
GCC_DIR='gcc'

#Do not change anything below here
VERSION = os.environ["MBED_INSTALLER_VERSION"] # Get version from env, set in CreateInstaller.sh
print("\r\nInstaller Version "+VERSION)
APP = ['run-mbed-cli.py']
APP_NAME = "MBED_CLI"
DATA_FILES = ['run-mbed-cli.sh',GCC_DIR,"bin","git","venv","VERSION.txt"]
OPTIONS = {
    'argv_emulation': True,
    'iconfile': './mbed-cli-logo.icns',
    # 'packages':['mbed','mbed_lstools','mbed_greentea','mbed_host_tests',"serial","bs4","jinja2","elftools","fuzzywuzzy","mercurial","hgdemandimport","hgext","hgext3rd"],
    # 'includes': "mbed,mbed_lstools,mbed_greentea,mbed_host_tests",
    'plist': {
        'CFBundleName': APP_NAME,
        'CFBundleDisplayName': APP_NAME,
        'CFBundleGetInfoString': "Run MBED CLI",
        'CFBundleIdentifier': "com.armmbed.osx.mbed-cli",
        'CFBundleVersion': VERSION,
        'CFBundleShortVersionString': VERSION,
        'NSHumanReadableCopyright': u"Copyright 2018 Arm Mbed All Rights Reserved",
        'CFBundleIconFile':'./mbed-cli-logo.icns'
    }
}


setup(
	name=APP_NAME,
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
